//
//  ViewController.swift
//  AV Foundation
//
//  Created by Pranjal Satija on 5/22/17.
//  Copyright © 2017 Pranjal Satija. All rights reserved.
//

import UIKit

class TakePhotoViewController: UIViewController {
    
    @IBOutlet fileprivate var captureButton: UIButton!
    
    ///Displays a preview of the video output generated by the device's cameras.
    @IBOutlet fileprivate var capturePreviewView: UIView!
    
    let cameraController = CameraController()
    var image: UIImage!
    override var prefersStatusBarHidden: Bool { return true }
}

extension TakePhotoViewController {
    override func viewDidLoad() {
        overrideUserInterfaceStyle = .light
        
        
        func configureCameraController() {
            cameraController.prepare {(error) in
                if let error = error {
                    print(error)
                }
                try? self.cameraController.displayPreview(on: self.capturePreviewView)
                
            }
        }
        
        func styleCaptureButton() {
            captureButton.layer.borderColor = UIColor.black.cgColor
            captureButton.layer.borderWidth = 2
            
            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
        }
        
        styleCaptureButton()
        configureCameraController()
        
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "toVerifySuccessScreen" {
            if let vc = segue.destination as? UINavigationController, let targetController = vc.topViewController as? VerifySuccessViewController {
                targetController.base64image = convertImageToBase64String(img: self.image)
            }
        }
    }
}

extension TakePhotoViewController {
    
    @IBAction func captureImage(_ sender: UIButton) {
        cameraController.captureImage {(image, error) in
            guard let image = image else {
                print(error ?? "Image capture error")
                return
            }
            self.image = image
            self.performSegue(withIdentifier: "toVerifySuccessScreen", sender: nil)
            
        }
    }
    
}
